apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: user-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: andy2025/user_service:latest
        ports:
        - containerPort: 8000

