services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      # - db
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "app_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  app_network:
    driver: bridge
